name: Go

on: workflow_call

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Check fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0  ]; then exit 1; fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot

      - name: Call init test script if found
        run: |
          if [[ -f "setup-tests.sh" ]]; then
            ./setup-tests.sh
          fi

      - name: Test
        run: |
          go test -race -cover -coverprofile=coverage.txt ./...

      - name: Push on codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
